# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63bdc63f8477f5c9e2906a2a4c336374e228993658a6d5dc7566025f43b17fc911cb5dbe4af0a48375ba6812846e67fc962d302210377492860c57fd55ef8d0d

test:
  secret_key_base: 71198492125171a7aea6bf41e44455b7b38535b2c1d42f79cd41b81ab9089fde43b99dcfa50a062b1709ad23db0f624642790399b5a263339c4b3fc8ff430e93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
